name: raffle

services:
  app:
    container_name: raffle-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: ${USER:-raffle}
        uid: ${USER_UID:-1001}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      - TAG=${TAG:-latest}
    env_file:
      - .env.production

  web:
    container_name: raffle-nginx
    image: nginx:1.21-alpine
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app
    env_file:
      - .env.production

  db:
    container_name: raffle-db
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "${SERVER_PORT_DB:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-homestead}
      - MYSQL_USER=${DB_USERNAME:-homestead}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - app-network
    env_file:
      - .env.production

  phpmyadmin:
    container_name: raffle-phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT_DB:-8080}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST:-db}
      - PMA_USER=${DB_USERNAME:-homestead}
      - PMA_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env.production

networks:
  app-network:
    driver: bridge